### PR TITLE
Quest level color in ItemRef tooltip title

### PR DESCRIPTION
**Pull request by Artur91425**

### CODE REVIEW

**Comment by Artur91425** [comment]
Before:
image
After:
image

**Comment by shagu** [comment]
If changing the title color of the quest tooltip, i think it should be done for TBC aswell.

**Comment by shagu** [comment]
I have ported the quest link colors here https://github.com/shagu/pfQuest/commit/d6cd7e7e1632bcbc7528980503b9084de2b38af0
Regarding the itemref title, I think it should be done on both vanilla and TBC.

**Comment by Artur91425** [comment]
image

**Comment by shagu** [comment]
Thanks. https://github.com/shagu/pfQuest/commit/b851ef2cac02806172989984e72393f40359cd88

**Pull request closed without merging**
