### PR TITLE
Grim Message quest fix and rename objects

### PR DESCRIPTION
**Pull request by KasVital**

### CODE REVIEW

**Comment by shagu** [comment]
Thanks, but those values are exported from the VMaNGOS databases.
If I'd merge this, it would be automatically overwritten by the next DB export.

**Comment by KasVital** [comment]
I hope this line [300016] = "Witherbark Village", stay

**Comment by shagu** [comment]
How does it freeze your client? It's only 3 objects: https://classicdb.ch/?object=300016

**Comment by KasVital** [comment]
Maybe because your logic in addon cant get normal name for this objects, idk

**Pull request closed without merging**
